apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: horizontal-scale
  namespace: db
spec:
  type: HorizontalScaling
  databaseRef:
    name: mongodb
  horizontalScaling:
    replicas: 4
    # shard: 
    #   shards: 1
    #   replicas: 2
    # mongos:
    #   replicas: 2
    # configServer:
    #   replicas: 1