apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: backup
  namespace: demo
spec:
  schedule: "*/1 * * * *"
  repository:
    name: repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mongodb
      namespace: db
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
    pod:
      serviceAccountName: cross-namespace-target-reader
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
