apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: demo
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8xMjM0NQ==
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM0NQ==
  RESTIC_PASSWORD: Y2hhbmdlaXQ=

