apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: demo
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # inside the `kind-control-plane`

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: demo
spec:
  storageClassName: "standard"
  volumeName: "task-pv-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi