apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: demo
spec:
  storageClassName: "standard"
  volumeName: "task-pv-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi