apiVersion: schema.kubedb.com/v1alpha1
kind: MongoDBDatabase
metadata:
  name: restore
  namespace: demo
spec:
  database:
    serverRef:
      name: checker
      namespace: dev
    config:
      name: songs
  vaultRef:
    name: vault
    namespace: demo
  accessPolicy:
    subjects:
      - name: "saname"
        namespace: dev
        kind: "ServiceAccount"
        apiGroup: ""
    defaultTTL: "15m"
    maxTTL: "200h"
  init:
    initialized: false
    snapshot:
      repository:
        name: repo
        namespace: demo
  deletionPolicy: Delete