# apiVersion: v1
# kind: Pod
# metadata:
#   name: try-pod
#   namespace: dev
# spec:
#   containers:
#     - name: test
#       volumeMounts:
#       image: nginx
#         - name: config-vol
#           mountPath: /etc/arnob
#   volumes:
#     - name: config-vol
#       configMap:
#         name: test-cm
#         items: # is items not specifed, every key in test-cm will be file name inside /etc/arnob directory
#           - key: examplefile  # now as specified, /etc/arnob contains one file named somename, with content of the value of examplefile key
#             path: somename

apiVersion: v1
kind: Pod
metadata:
  name: try-pod
  namespace: dev
spec:
  containers:
  - name: test
    image: nginx
    volumeMounts:
    - mountPath: /var/local/bbb
      name: mydir
  volumes:
  - name: mydir
    hostPath:
      path: /var/local/somedir/aaa # Ensure the file directory is created.
      type: DirectoryOrCreate