apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2022-02-23T11:39:30Z"
  generation: 1
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mongodbs.kubedb.com
    mongodb.kubedb.com/node.arbiter: mongodb-arbiter
  name: mongodb-arbiter
  namespace: db
  ownerReferences:
  - apiVersion: kubedb.com/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: MongoDB
    name: mongodb
    uid: dc71d6e6-1f48-43d7-84db-9187365823cf
  resourceVersion: "512635"
  uid: 0176445c-e2f5-4125-9670-067876ab38b8
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/managed-by: kubedb.com
      app.kubernetes.io/name: mongodbs.kubedb.com
      mongodb.kubedb.com/node.arbiter: mongodb-arbiter
  serviceName: mongodb-arbiter-pods
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: kubedb.com
        app.kubernetes.io/name: mongodbs.kubedb.com
        mongodb.kubedb.com/node.arbiter: mongodb-arbiter
    spec:
      containers:
      - args:
        - --dbpath=/data/db
        - --auth
        - --bind_ip_all
        - --port=27017
        - --ipv6
        - --tlsMode=disabled
        - --replSet=replicaset
        - --keyFile=/data/configdb/key.txt
        - --clusterAuthMode=keyFile
        command:
        - mongod
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: REPLICA_SET
          value: replicaset
        - name: AUTH
          value: "true"
        - name: SSL_MODE
          value: disabled
        - name: CLUSTER_AUTH_MODE
          value: keyFile
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: mongodb-auth
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-auth
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: mongo:4.4.6
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - /init-scripts/peer-finder -on-start=/init-scripts/arbiter.sh -service=mongodb-arbiter-pods
        name: mongodb
        ports:
        - containerPort: 27017
          name: db
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /work-dir
          name: workdir
        - mountPath: /data/configdb
          name: config
        - mountPath: /data/db
          name: datadir
        - mountPath: /init-scripts
          name: init-scripts
      - args:
        - run
        - --db-name=mongodb
        - --db-kind=MongoDB
        - --logtostderr=true
        - --alsologtostderr=false
        - --v=3
        - --stderrthreshold=2
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: mongodb-auth
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-auth
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: kubedb/replication-mode-detector:v0.12.0
        imagePullPolicy: IfNotPresent
        name: replication-mode-detector
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - -c
        - "\n\t\t\techo \"running install.sh\"\n\t\t\t/scripts/install.sh"
        command:
        - /bin/sh
        env:
        - name: SSL_MODE
          value: disabled
        image: arnobkumarsaha/mongodb-init:hello
        imagePullPolicy: IfNotPresent
        name: copy-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/configdb
          name: config
        - mountPath: /init-scripts
          name: init-scripts
        - mountPath: /var/run/mongodb/tls
          name: certdir
        - mountPath: /keydir-readonly
          name: keydir
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: workdir
      - emptyDir: {}
        name: init-scripts
      - emptyDir: {}
        name: certdir
      - name: keydir
        secret:
          defaultMode: 256
          secretName: mongodb-key
      - emptyDir: {}
        name: config
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
      storageClassName: standard
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mongodb-arbiter-58bb4b4846
  observedGeneration: 1
  replicas: 1
  updateRevision: mongodb-arbiter-58bb4b4846
  updatedReplicas: 1
