apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: mongo-secret-engine
  namespace: try
spec:
  vaultRef:
    name: vault
    namespace: demo
  mongodb:
    databaseRef:
      name: mongodb
      namespace: try
    pluginName: "mongodb-database-plugin"
