apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2022-02-24T05:12:27Z"
  generation: 1
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mongo
  namespace: db
  ownerReferences:
  - apiVersion: kubedb.com/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: MongoDB
    name: mongo
    uid: 43dcd3a7-a65b-4ba0-a3d9-52ef56d18a5d
  resourceVersion: "535269"
  uid: 6ea19ea3-fb39-4139-a9ea-33617557e69f
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongo
      app.kubernetes.io/managed-by: kubedb.com
      app.kubernetes.io/name: mongodbs.kubedb.com
  serviceName: mongo-pods
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: mongo
        app.kubernetes.io/managed-by: kubedb.com
        app.kubernetes.io/name: mongodbs.kubedb.com
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: mongo
                  app.kubernetes.io/managed-by: kubedb.com
                  app.kubernetes.io/name: mongodbs.kubedb.com
              namespaces:
              - db
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: mongo
                  app.kubernetes.io/managed-by: kubedb.com
                  app.kubernetes.io/name: mongodbs.kubedb.com
              namespaces:
              - db
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 50
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mongo
      serviceAccountName: mongo
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
      storageClassName: standard
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mongo-dc4f58ccd
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: mongo-dc4f58ccd
  updatedReplicas: 1


volumes:
- emptyDir: {}
  name: workdir
- emptyDir: {}
  name: init-scripts
- emptyDir: {}
  name: certdir
- emptyDir: {}
  name: config


initContainers:
- args:
  - -c
  - "\n\t\t\techo \"running install.sh\"\n\t\t\t/scripts/install.sh"
  command:
  - /bin/sh
  env:
  - name: SSL_MODE
    value: disabled
  image: arnobkumarsaha/mongodb-init:hello
  imagePullPolicy: IfNotPresent
  name: copy-config
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
  - mountPath: /data/configdb
    name: config
  - mountPath: /init-scripts
    name: init-scripts
  - mountPath: /var/run/mongodb/tls
    name: certdir
      

containers:
- args:
  - --dbpath=/data/db
  - --auth
  - --bind_ip_all
  - --port=27017
  - --ipv6
  - --tlsMode=disabled
  env:
  - name: SSL_MODE
    value: disabled
  - name: MONGO_INITDB_ROOT_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: mongo-auth
  - name: MONGO_INITDB_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: mongo-auth
  - name: POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  image: mongo:4.4.6
  imagePullPolicy: IfNotPresent
  livenessProbe:
    exec:
      command:
      - bash
      - -c
      - "set -x; if [[ $(mongo admin --host=localhost  --username=$MONGO_INITDB_ROOT_USERNAME
        --password=$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase=admin
        --quiet --eval \"db.adminCommand('ping').ok\" ) -eq \"1\" ]]; then \n
        \         exit 0\n        fi\n        exit 1"
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  name: mongodb
  ports:
  - containerPort: 27017
    name: db
    protocol: TCP
  readinessProbe:
    exec:
      command:
      - bash
      - -c
      - "set -x; if [[ $(mongo admin --host=localhost  --username=$MONGO_INITDB_ROOT_USERNAME
        --password=$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase=admin
        --quiet --eval \"db.adminCommand('ping').ok\" ) -eq \"1\" ]]; then \n
        \         exit 0\n        fi\n        exit 1"
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
  - mountPath: /data/db
    name: datadir
  - mountPath: /data/configdb
    name: config
  - mountPath: /init-scripts
    name: init-scripts
