apiVersion: engine.kubevault.com/v1alpha1
kind: MongoDBRole
metadata:
  name: reader-role
  namespace: dev
spec:
  secretEngineRef:
    name: mongo-secret-engine
  creationStatements:
    - '{ "db": "mydb", "roles": [{"role": "read"}] }'
---
apiVersion: engine.kubevault.com/v1alpha1
kind: MongoDBRole
metadata:
  name: reader-writer-role
  namespace: dev
spec:
  secretEngineRef:
    name: mongo-secret-engine
  creationStatements:
    - '{ "db": "mydb", "roles": [{ "role": "readWrite" }] }'
---
apiVersion: engine.kubevault.com/v1alpha1
kind: SecretAccessRequest
metadata:
  name: read-access-req
  namespace: dev
spec:
  roleRef:
    kind: MongoDBRole
    name: reader-role
  subjects:
    - kind: ServiceAccount
      name: readonly-user
      namespace: user-2
---
apiVersion: engine.kubevault.com/v1alpha1
kind: SecretAccessRequest
metadata:
  name: read-write-access-req
  namespace: dev
spec:
  roleRef:
    kind: MongoDBRole
    name: reader-writer-role
  subjects:
    - kind: ServiceAccount
      name: readwrite-user
      namespace: user-1