apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: restored-mgo
  namespace: stash-try
spec:
  version: "4.4.6"
  replicas: 3
  replicaSet:
    name: "restore-rs"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
  init:
    waitForInitialRestore: true