apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: mongo-backup
  namespace: db
spec:
  schedule: "*/1 * * * *"
  task:
    name: mongodb-backup-4.4.6
    namespace: db
  repository:
    name: minio-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mongodb # mng-shrd
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true