apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-mgo-restore
  namespace: db
spec:
  task:
    name: mongodb-restore-4.4.6
  repository:
    name: local-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mng-shrd
  rules:
  - snapshots: [latest]