apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: nginx-deployment
    uid: f151eb01-eb72-42d5-8f37-b4992e976c32
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]