apiVersion: engine.kubevault.com/v1alpha1
kind: MongoDBRole
metadata:
  name: admin-role
  namespace: try
spec:
  secretEngineRef:
    name: mongodbdatabase-sample-secret-engine
  creationStatements:
    - '{ "db": "mydb", "roles": [{ "role": "dbAdmin" }] }'
  revocationStatements:
    - '{ "db": "mydb", "roles": [{ "role": "dbAdmin" }] }'
