apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: mongo-se
  namespace: try
spec:
  mongodb:
    databaseRef:
      name: mgo-tls
      namespace: try
    pluginName: mongodb-database-plugin
  vaultRef:
    name: vault
    namespace: try