apiVersion: schema.kubedb.com/v1alpha1
kind: MongoDBDatabase
metadata:
  name: sample
  namespace: dev
spec:
  databaseRef:
    name: mongodb
    namespace: db
  vaultRef:
    name: "vault"
    namespace: "demo"
  databaseSchema:
    name: "mydb"
  subjects:
    - name: "sa_name"
      kind:
        apiVersion: "v1"
        kind: "ServiceAccount"
      namespace: "dev"
#  init:
#    initialized: false
#    script:
#      scriptPath: "/etc/config"
#      volumeSource:
#        configMap:
#          name: "test-cm"
#    podTemplate:
#      spec:
#        env:
#          - name: "HAVE_A_TRY"
#            value: "whoo! It works"
  restore:
    repository:
      name: minio-repo
      namespace: db
    snapshot:  latest
  autoApproval: true
  deletionPolicy: "Delete"

#  ```
#   From RestoreSession.Status describe
#  Stats:
#    Error:      2022-01-06T13:00:56.023+0000  Failed: I/O failure reading beginning of archive: EOF 2022-01-06T13:00:56.023+0000
#      0 document(s) restored successfully. 0 document(s) failed to restore.
#    Phase:      Failed


#  Log on restore pod :
#  I0106 13:00:55.301536       1 restore.go:284] processing backupOptions for  replicaset/mongodb-0.mongodb-pods.db.svc,mongodb-1.mongodb-pods.db.svc,mongodb-2.mongodb-pods.db.svc
#  I0106 13:00:55.301566       1 restore.go:359] processing restore.
#  I0106 13:00:55.301570       1 utils.go:68] Checking database connection
#  I0106 13:00:55.302344       1 commands.go:277] Dumping backed up data
#latest snapshot for criteria not found: no snapshot found Paths:[] Hosts:[host-0]
#2022-01-06T13:00:56.023+0000	Failed: I/O failure reading beginning of archive: EOF
#  2022-01-06T13:00:56.023+0000	0 document(s) restored successfully. 0 document(s) failed to restore.
#I0106 13:00:58.001218       1 log.go:184] FLAG: --bucket="backup-mongo"



#  One little issue :: Suppose I am working on a database by logged in with my vault-created credentials.
#  In that time, DBAdmin deleted the MongoDbDatabaseSchema. Which will also delete the vault-created credentials.
#  The problem is ,  As I am already logged in , I can simply work with