apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-go-test
spec:
  template:
    spec:
      containers:
      - name: kubernetes-go-test
        image: arnobkumarsaha/kubernetes-go-test
        imagePullPolicy: Always
      restartPolicy: Never
