apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mongodb
  namespace: db
spec:
  version: "4.4.6"
  replicaSet:
    name: "replicaset"
  replicas: 2
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  #terminationPolicy: WipeOut
  #init:
  #  waitForInitialRestore: true
  # terminationPolicy and init is added when trying to restore

